local u = require("netizen.utils")
local pal = require("netizen.palette")

return {
	syn = {
		string     = pal.green,
		variable   = pal.fg2_5,
		number     = pal.fg3,
		constant   = pal.red,
		identifier = pal.fg1,
		parameter  = pal.blue,
		func       = pal.cyan,
		statement  = pal.blue,
		keyword    = pal.magenta,
		operator   = pal.cyan,
		preproc    = pal.red,
		type       = pal.magenta,
		regex      = pal.red,
		deprecated = pal.fg3,
		punct      = pal.fg3,
		comment    = pal.fg4_5,
		special1   = pal.fg3_5,
		special2   = pal.yellow,
		special3   = pal.magenta,
		error      = pal.xRed,
		errorBg    = u.blend(pal.xRed, pal.bg0_5, 0.66),
		ok         = pal.hiGreen,
		warning    = pal.hiYellow,
		search     = pal.hiGreen,
		searchbg   = u.blend (pal.hiGreen, pal.bg0_5, 0.5),
		info       = pal.hiBlue,
		hint       = pal.hiCyan,
		add        = pal.hiGreen,
		delete     = pal.hiRed,
		change     = pal.hiBlue,
		textfg     = pal.hiCyan,
		text       = u.blend(pal.cyan, pal.bg0_5, 0.5),
		added      = u.blend(pal.green, pal.bg0_5, 0.5),
		removed    = u.blend(pal.red, pal.bg0_5, 0.5),
		changed    = u.blend(pal.blue, pal.bg0_5, 0.5),
	},
	ui = {
		bg_gutter = pal.bg_0,
		bg        = pal.bg0_5,
		bg_dim    = pal.bg0,
		bg_sel    = pal.bg2,
		fg        = pal.fg1,
		fg_dim    = pal.fg2,
		fg_sel    = pal.fg0,
		status    = pal.bg2,
		pmenu = {
			bg     = pal.bg2,
			sel    = pal.bg3_5,
		},
		nontext   = pal.fg5,
	},
}
